### PR TITLE
2 the project needs a grouped navbar set

### PR DESCRIPTION
**Pull request by Vctcode**
- Created the navbar set including the sticky and non-sticky part.
- Made the responsiveness for both desktop, tab and mobile
- Created separate CSS for navbar set
- Created separate JS file for navbar set to show and hide menu on tab and mobile screens

### CODE REVIEW

**Comment by Vctcode** [comment]
Kindly review.

**Comment by Okpainmo** [comment]
I'll be on it - well-done @Vctcode

**Comment by Okpainmo** [comment]
Weldone @Vctcode.

**Comment by Okpainmo** [comment]
close #2

**Pull request merged**
