### PR TITLE
Issue 6_the-project-needs-a-checkout-page resolved

### PR DESCRIPTION
**Pull request by Vctcode**
@Okpainmo For your awareness, below is the summary of the issue resolved.

A checkout page that shows list of all items from Cart, total amount to pay and accepts details for shipping.

### Method of Solution
- [x] created the markup for the project from main page and imported the footer from existing code.
- [x] styled the main page
- [x] created the navigation for the page
- [x] made responsiveness
- [x] linked the page to the Cart page of the project

### CODE REVIEW

**Review by Okpainmo — COMMENTED** [review]
Weldone @Vctcode.

Your PR is simply at a pro level now.
But are you sure you've completed the task as should be - I mean the complete checkout page?

Remember PRs are only to be made after completing a task.

**Comment by Vctcode** [comment]
@Okpainmo 

The task marked above has been completed.

**Comment by Vctcode** [comment]
Hello @Okpainmo,

This is a reminder for a review on this issue.

**Review by Okpainmo — APPROVED** [review]
Weldone @Vctcode. I am proud of how well you've improved.

**Pull request merged**
